import { AppProps } from 'next/dist/next-server/lib/router/router';
import Head from 'next/head';
import { FunctionComponent } from 'react';
import '../styles/globals.css';

const MyApp: FunctionComponent<AppProps> = ({ Component, pageProps }) => {
    return (
        <>
            <Head>
                <title>Applcation</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />;
        </>
    );
};

export default MyApp;
